; Hormachuelos — warmer NSIS strings (must include every Tauri LangString key)

LangString addOrReinstall ${LANG_ENGLISH} "Add or reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Hormachuelos is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already on this PC. Choose what to do next, then click Next."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is still open.$\r$\n$\r$\nClose it so setup can continue."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is still open.$\r$\n$\r$\nClick OK to close it automatically, then continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose how you want to continue"
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the current install"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (downgrade without uninstall is disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close {{product_name}}. Quit it manually, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Preparing Microsoft Edge WebView2…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer Hormachuelos is already installed. It’s usually better to keep that build. If you still want this older version, uninstall the current one first. Choose an option and click Next."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed. Uninstalling first is recommended. Choose an option and click Next."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for silent installs. Please use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Could not uninstall the previous version."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 setup failed. Hormachuelos needs it to run — restart the installer after fixing WebView2."
LangString webview2DownloadError ${LANG_ENGLISH} "Could not download WebView2 ($0). Check your connection and try again."
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 downloaded — finishing setup…"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2…"
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 install failed (exit code $1). Try again or install WebView2 manually."
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 is ready."
LangString deleteAppData ${LANG_ENGLISH} "Also delete Hormachuelos app data"
